# Generated by Django 4.2.20 on 2025-04-15 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArKategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kavezo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('cim', models.CharField(max_length=255)),
                ('hangulat', models.CharField(blank=True, choices=[('nyugodt', 'Nyugodt'), ('barátságos', 'Barátságos'), ('forgalmas', 'Forgalmas'), ('romantikus', 'Romantikus')], default='nyugodt', help_text='Válassza ki a kávézó hangulatát.', max_length=50)),
                ('arkategoriak', models.CharField(blank=True, choices=[('olcsó', 'Olcsó'), ('közepes', 'Közepes'), ('drága', 'Drága')], default='közepes', help_text='Pl. alacsony, közepes vagy magas árkategória.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('csatlakozas_datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('leiras', models.TextField(blank=True, null=True)),
                ('ar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termekek', to='kavezok.kavezo')),
            ],
        ),
        migrations.CreateModel(
            name='Rendeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavezok.kavezo')),
                ('termekek', models.ManyToManyField(to='kavezok.termek')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kedvenc_kave', models.CharField(default='Espresso', help_text='A felhasználó kedvenc kávéja', max_length=255)),
                ('hangulat', models.CharField(choices=[('csendes', 'Csendes'), ('forgalmas', 'Forgalmas')], default='csendes', max_length=50)),
                ('ar', models.CharField(choices=[('alacsony', 'Alacsony'), ('közepes', 'Közepes'), ('magas', 'Magas')], default='közepes', max_length=10)),
                ('felhasznalo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nyitvatartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nap', models.CharField(choices=[('hetfo', 'Hétfő'), ('kedd', 'Kedd'), ('szerda', 'Szerda'), ('csutortok', 'Csütörtök'), ('pentek', 'Péntek'), ('szombat', 'Szombat'), ('vasarnap', 'Vasárnap')], max_length=10)),
                ('nyitas', models.TimeField(default=datetime.time(8, 0), help_text='Nyitási idő')),
                ('zaras', models.TimeField(default=datetime.time(22, 0), help_text='Zárási idő')),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nyitvatartasok', to='kavezok.kavezo')),
            ],
        ),
        migrations.CreateModel(
            name='Kedvezmeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neve', models.CharField(max_length=100)),
                ('leiras', models.TextField()),
                ('ervenyes_tol', models.DateField()),
                ('ervenyes_ig', models.DateField()),
                ('ar_szazalek', models.PositiveIntegerField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kedvezmenyek', to='kavezok.kavezo')),
            ],
        ),
        migrations.CreateModel(
            name='Foglalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=datetime.datetime.now)),
                ('szemelyek_szama', models.PositiveIntegerField()),
                ('allapot', models.CharField(choices=[('függő', 'Függő'), ('megerősített', 'Megerősített'), ('lemondott', 'Lemondott')], default='függő', max_length=20)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavezok.kavezo')),
            ],
        ),
        migrations.CreateModel(
            name='Ertekeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontszam', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavezok.kavezo')),
            ],
        ),
        migrations.CreateModel(
            name='AdminErtekeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ertekeles', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('letrehozas_datum', models.DateTimeField(auto_now_add=True)),
                ('kavezo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavezok.kavezo')),
            ],
        ),
    ]
