# Generated by Django 4.2.20 on 2025-04-15 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kavezok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KosarTetel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.PositiveIntegerField(default=1)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kosar_tetelek', to=settings.AUTH_USER_MODEL)),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavezok.termek')),
            ],
        ),
    ]
