# Generated by Django 4.2.20 on 2025-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0002_kosartetel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kedvezmeny',
            name='kavezo',
        ),
        migrations.RemoveField(
            model_name='kedvezmeny',
            name='leiras',
        ),
        migrations.RemoveField(
            model_name='kedvezmeny',
            name='neve',
        ),
        migrations.AddField(
            model_name='kedvezmeny',
            name='nev',
            field=models.CharField(default='Alapértelmezett kedvezmény', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kedvezmeny',
            name='aktiv',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='kedvezmeny',
            name='ar_szazalek',
            field=models.PositiveIntegerField(),
        ),
    ]
