# Generated by Django 4.2.20 on 2025-04-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0003_remove_kedvezmeny_kavezo_remove_kedvezmeny_leiras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kedvezmeny',
            name='kavezo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kedvezmenyek', to='kavezok.kavezo'),
        ),
        migrations.AddField(
            model_name='kedvezmeny',
            name='kod',
            field=models.CharField(default='Kedvezmény default', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kedvezmeny',
            name='leiras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kedvezmeny',
            name='minimum_osszeg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kedvezmeny',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
