# Generated by Django 4.2.20 on 2025-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0004_kedvezmeny_kavezo_kedvezmeny_kod_kedvezmeny_leiras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('szazalek', models.PositiveIntegerField(default=0)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
    ]
