# Generated by Django 4.2.20 on 2025-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0005_kupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kavezo',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
