# Generated by Django 4.2.20 on 2025-04-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0006_kavezo_google_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendelesTetel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.PositiveIntegerField(default=1)),
                ('ar', models.PositiveIntegerField(default=0)),
                ('rendeles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetel_lista', to='kavezok.rendeles')),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavezok.termek')),
            ],
        ),
    ]
