# Generated by Django 4.2.20 on 2025-04-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0011_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='pontok',
            new_name='total_points',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='utolso_belepes',
        ),
    ]
