# Generated by Django 4.2.20 on 2025-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0012_rename_pontok_profil_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='utolso_belepes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
