# Generated by Django 4.2.20 on 2025-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0013_profil_utolso_belepes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='checkin_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
