# Generated by Django 4.2.20 on 2025-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0014_profil_checkin_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='last_spin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
