# Generated by Django 4.2.20 on 2025-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0015_profil_last_spin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='created',
            field=models.DateField(),
        ),
    ]
