# Generated by Django 4.2.20 on 2025-04-29 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kavezok', '0016_alter_checkin_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ertekeles',
            name='felhasznalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ertekeles',
            name='kavezo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ertekelesek', to='kavezok.kavezo'),
        ),
        migrations.AlterField(
            model_name='ertekeles',
            name='megjegyzes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ertekeles',
            name='pontszam',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 csillag'), (4, '4 csillag'), (3, '3 csillag'), (2, '2 csillag'), (1, '1 csillag')], verbose_name='Értékelés'),
        ),
    ]
