# Generated by Django 4.2.20 on 2025-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavezok', '0017_alter_ertekeles_felhasznalo_alter_ertekeles_kavezo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foglalas',
            name='emlekezteto_kuldve',
            field=models.BooleanField(default=False),
        ),
    ]
